/**
 * Shared application types. Domain types are generated by Prisma and imported
 * from @core-cps/database; UI/view-model types live here.
 */
export type Role =
  | "PROJECT_USER"
  | "CPS_COORDINATOR"
  | "WAREHOUSE"
  | "CPS_MANAGER"
  | "LEADERSHIP"
  | "ADMIN";
